[9.x] Terjemahan untuk file views.md
lara-army/dokumentasi-laravel pull request #100
Opened 2023-01-14 12:12 UTC by sensasi-delight

close #6 

Rekan-rekan kolaborator tersayang, mohon meninjau terjemahan yang saya kerjakan. terima kasih. 🍻

2023-01-14 14:08 UTC, wokeh requested changes
Great job bro, berikut request perubahan dr sy

View memisahkan logika controller/aplikasi
View memisahkan controller/logika aplikasi

templat view
template view

**Komposer tampilan** adalah callback
**View Composer** adalah callback

sisanya tinggal ngikutin model2 tsb

2023-01-14 18:17 UTC, sensasi-delight commented
kok kayaknya kamu bukan melihat perubahan yang terbaru ya pak? @wokeh

2023-01-15 12:31 UTC, theozebua commented on views.md
> +- [Optimasi _View_](#optimizing-views)
Bagaimana dengan _view_ 👉🏼 tampilan?

2023-01-15 13:46 UTC, sensasi-delight commented on views.md
> +- [Optimasi _View_](#optimizing-views)
> Bagaimana dengan _view_ 👉🏼 tampilan?

ketika kata "_view_" bermaksud _view_ dalam MVC atau file untuk _view_ maka saya biarkan tetap _view_. namun ketika merujuk ke konsep, beberapa kata saya terjemahkan menjadi "tampilan"

2023-01-15 16:51 UTC, theozebua approved these changes
LGTM

2023-01-15 16:52 UTC, theozebua commented on views.md
> +- [Optimasi _View_](#optimizing-views)
Okay

2023-01-17 01:00 UTC, MeizalunaWulandari approved these changes

2023-01-17 02:07 UTC, merged