[9.x] session.md
lara-army/dokumentasi-laravel pull request #103
Opened 2023-01-21 03:07 UTC by sensasi-delight

close #10 

rekan-rekan kontributor tersayang, mohon untuk melakukan peninjauan terhadap hasil terjemahan yang telah saya lakukan. terima kasih 🍻

2023-01-21 04:35 UTC, MeizalunaWulandari commented on session.md
> +Secara _default_, Laravel mengizinkan semua _request_ untuk menggunakan _session_ yang sama untuk dieksekusi secara bersamaan. Sebagai contoh, jika Anda menggunakan sebuah pustaka HTTP JJavaScrip unt
JavaScript typo

2023-01-21 06:43 UTC, sensasi-delight commented on session.md
> +Secara _default_, Laravel mengizinkan semua _request_ untuk menggunakan _session_ yang sama untuk dieksekusi secara bersamaan. Sebagai contoh, jika Anda menggunakan sebuah pustaka HTTP JJavaScrip unt
consider it done boss

2023-01-21 06:58 UTC, theozebua requested changes

2023-01-21 06:58 UTC, theozebua commented on session.md
> +    - [Melakukan _Retrieve_ Data](#retrieving-data)
Melakukan _Retrieve_ Data ini bisa diganti dengan Mengambil data.

2023-01-21 07:31 UTC, sensasi-delight commented on session.md
> +    - [Melakukan _Retrieve_ Data](#retrieving-data)
retrieve vs mengambil

cc: @wokeh @MeizalunaWulandari

2023-01-21 13:41 UTC, wokeh commented on session.md
> +    - [Melakukan _Retrieve_ Data](#retrieving-data)
kekna di konteks ini setuju pake kata mengambil, kadang di konteks lain gw pake kata me-retrieve :)

2023-01-21 14:22 UTC, MeizalunaWulandari commented on session.md
> +    - [Melakukan _Retrieve_ Data](#retrieving-data)
@sensasi-delight sesuai demokrasi aja, jadi ya "mengambil" juga

2023-01-21 15:08 UTC, sensasi-delight commented on session.md
> +    - [Melakukan _Retrieve_ Data](#retrieving-data)
shap

2023-01-22 04:53 UTC, theozebua commented on session.md
> +    - [Melakukan _Retrieve_ Data](#retrieving-data)
Udah diperbaiki kah? Biar aku approve ni

2023-01-22 13:21 UTC, MeizalunaWulandari approved these changes

2023-01-22 17:36 UTC, sensasi-delight commented on session.md
> +    - [Melakukan _Retrieve_ Data](#retrieving-data)
sir yes sir

2023-01-24 02:43 UTC, merged