translate structure folder
lara-army/dokumentasi-laravel pull request #105
Opened 2023-01-22 15:13 UTC by muchfahmiarif

Translate to Indonesia pada file `structure.md`

2023-01-22 15:32 UTC, sensasi-delight commented
wah keren pak, agak maleman aku ripiw ✌🏻

2023-01-22 18:06 UTC, sensasi-delight commented on structure.md
> +## Direktori Akar
"Root Directory" enaknya diterjemahin jadi "Direktori Akar" atau "Direktori _Root_"?

cc: @wokeh @theozebua @MeizalunaWulandari

2023-01-23 00:12 UTC, MeizalunaWulandari commented on structure.md
> +## Direktori Akar
root italic

2023-01-23 00:12 UTC, MeizalunaWulandari commented on structure.md
> +## Direktori Akar
root italic

2023-01-23 00:38 UTC, MeizalunaWulandari commented on structure.md
> +`app` direktori berisi kode inti aplikasi anda. Kami akan menjelajahi direktori ini lebih detail segera; namun, hampir semua _class_ di aplikasi anda akan berada di direktori ini.
harusnya "kita" bukan kami, karna klo kami sama kaya "kalian" lawan bicara ga dimasukan

2023-01-23 00:38 UTC, MeizalunaWulandari commented on structure.md
> +Direktori `database` berisi migrasi database, pabrik model, dan _seeds_. Jika mau, Anda juga dapat menggunakan direktori ini untuk menyimpan database SQLite.
Kayanya Factory ga perlu di translate karna itu nama

2023-01-23 00:38 UTC, MeizalunaWulandari commented on structure.md
> +Direktori `storage/app/public` dapat digunakan untuk menyimpan _file_ yang dibuat pengguna, seperti avatar profil, yang harus dapat diakses publik. Anda harus membuat tautan simbolis di `public/stora
Perintah artisan, samain kya translate lain

2023-01-23 00:38 UTC, MeizalunaWulandari commented on structure.md
> +## Direktori Aplikasi
App, ga perlu di translate juga kya nama

2023-01-24 02:47 UTC, theozebua commented on structure.md
> +## Direktori Akar
> "Root Directory" enaknya diterjemahin jadi "Direktori Akar" atau "Direktori _Root_"?
> 
> cc: @wokeh @theozebua @MeizalunaWulandari

Direktori _Root_

2023-01-24 13:29 UTC, muchfahmiarif commented on structure.md
> +## Direktori Akar
wokeehh makasii pak-bapak dan buk-ibuk nanti saya repisi

2023-01-24 13:34 UTC, muchfahmiarif commented on structure.md
> +Direktori `database` berisi migrasi database, pabrik model, dan _seeds_. Jika mau, Anda juga dapat menggunakan direktori ini untuk menyimpan database SQLite.
siapp bu

2023-01-24 13:38 UTC, muchfahmiarif commented on structure.md
> +Direktori `storage/app/public` dapat digunakan untuk menyimpan _file_ yang dibuat pengguna, seperti avatar profil, yang harus dapat diakses publik. Anda harus membuat tautan simbolis di `public/stora
yg _`command`_ itu di delete ya?

2023-01-24 17:41 UTC, muchfahmiarif commented
sudah aku benerin, tolong di ripiew manteman di commit [`1fbf5b8`](https://github.com/lara-army/dokumentasi-laravel/pull/105/commits/1fbf5b8c02ac7c4c939ae3d50543076782ad244b)

2023-01-25 00:05 UTC, MeizalunaWulandari commented on structure.md
> +Direktori `storage/app/public` dapat digunakan untuk menyimpan _file_ yang dibuat pengguna, seperti avatar profil, yang harus dapat diakses publik. Anda harus membuat tautan simbolis di `public/stora
@muchfahmiarif 
Ga dihapus diganti aja jadi
Perintah artisan

2023-01-25 02:34 UTC, theozebua requested changes

2023-01-25 02:34 UTC, theozebua commented on structure.md
> +File `web.php` berisi rute yang ditempatkan `RouteServiceProvider` di grup middleware `web`, yang menyediakan status sesi, perlindungan CSRF, dan enkripsi cookie. Jika aplikasi anda tidak menawarkan
Untuk kata-kata yang tidak diterjemahkan (kata asing), sebaiknya menggunakan _italic_.
- "... di grup middleware ..." 👉🏼 "... di grup _middleware_ ..."
- "... dan enkripsi cookie. ..." 👉🏼 "... dan enkripsi _cookie_. ..."

Mungkin masih ada di beberapat tempat lagi, jadi mohon di cek kembali ya 😄

2023-01-25 08:11 UTC, muchfahmiarif commented on structure.md
> +File `web.php` berisi rute yang ditempatkan `RouteServiceProvider` di grup middleware `web`, yang menyediakan status sesi, perlindungan CSRF, dan enkripsi cookie. Jika aplikasi anda tidak menawarkan
ashiapp

2023-01-25 13:03 UTC, theozebua approved these changes
Nice 👍🏻

2023-01-26 01:44 UTC, muchfahmiarif commented
list link nya tetep pake _default_ ya om, tapi teks nya ke indo? bener gitu bukan @sensasi-delight ?

2023-01-26 01:48 UTC, sensasi-delight commented
betul, tapi sementara ini belum ditetapkan apakah `<a>` harus sama seperti `#heading` atau tidak. sebelum liat hasilnya di hosting nanti 😁👍🏻

2023-01-26 03:19 UTC, muchfahmiarif commented
asiapp :thumbsup:

2023-01-28 03:29 UTC, MeizalunaWulandari commented on structure.md
>  Berbagai direktori lain akan dibuat di dalam direktori `app` saat anda menggunakan perintah `make` pada artisan _command_ untuk membuat kelas. Jadi, misalnya, direktori `app/Jobs` tidak akan ada samp
"menghasilkan kelas pekerjaan." Ini jobnya nama file hasil make:job, jadi ga perlu di translate juga

2023-01-29 16:10 UTC, sensasi-delight commented on structure.md
>  Berbagai direktori lain akan dibuat di dalam direktori `app` saat anda menggunakan perintah `make` pada artisan _command_ untuk membuat kelas. Jadi, misalnya, direktori `app/Jobs` tidak akan ada samp
ayo fix ini pak @muchfahmiarif

2023-01-29 16:19 UTC, sensasi-delight commented on structure.md
>  Berbagai direktori lain akan dibuat di dalam direktori `app` saat anda menggunakan perintah `make` pada artisan _command_ untuk membuat kelas. Jadi, misalnya, direktori `app/Jobs` tidak akan ada samp
baris 114:
Berbagai direktori lain akan dibuat di dalam direktori `app` saat anda menggunakan perintah `make` pada artisan _command_ untuk membuat kelas. Jadi, misalnya, direktori `app/Jobs` tidak akan ada sampai anda menjalankan perintah Artisan `make:job` untuk menghasilkan kelas ~~pekerjaan~~ `Job`.

2023-01-29 16:46 UTC, sensasi-delight commented on structure.md
> +Berbagai direktori lain akan dibuat di dalam direktori `app` saat Anda menggunakan perintah `make` pada perintah Artisan untuk membuat beberapa kelas. Jadi, misalnya, direktori `app/Jobs` tidak akan
`Job` huruf awal kapital karena mengacu pada nama kelas

2023-01-29 17:28 UTC, sensasi-delight approved these changes
LGTM 🍻

2023-01-29 17:28 UTC, merged