[9.x] logging.md
lara-army/dokumentasi-laravel pull request #108
Opened 2023-01-23 19:28 UTC by sensasi-delight

close #13 

rekan-rekan kontributor tersayang, mohon untuk meninjau hasil terjemahan yang telah saya lakukan. terima kasih 🍻

2023-01-24 09:44 UTC, theozebua requested changes

2023-01-24 09:44 UTC, theozebua commented on logging.md
> +- [Kostumisasi Kanal Monolog](#monolog-channel-customization)
Bukan "Kostumisasi" tapi "Kustomisasi"

![image](https://user-images.githubusercontent.com/87429668/214258777-e6822998-407d-4c91-8317-9777337e6314.png)
![image](https://user-images.githubusercontent.com/87429668/214259093-92d36e43-f642-476f-ab3e-1c5edc87aaee.png)

2023-01-25 16:58 UTC, sensasi-delight commented on logging.md
> +- [Kostumisasi Kanal Monolog](#monolog-channel-customization)
done at https://github.com/lara-army/dokumentasi-laravel/pull/108/commits/5767bb62f7dac99a525a67e1b4a5fa1b1ed95f2d boss

2023-01-25 17:10 UTC, theozebua commented on logging.md
> +- [Kostumisasi Kanal Monolog](#monolog-channel-customization)
Mantap 👍🏼

2023-01-25 17:11 UTC, theozebua approved these changes

2023-01-29 16:40 UTC, muchfahmiarif approved these changes

2023-01-29 16:52 UTC, merged