Frontend translate
lara-army/dokumentasi-laravel pull request #109
Opened 2023-01-28 04:12 UTC by muchfahmiarif

gaes tolong di ripiw yaa
terima kasih

2023-01-28 14:46 UTC, sensasi-delight requested changes
revisi boskuuu

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Lainnya, lebih memilih untuk tetap menggunakan bahasa _backend_ yang mereka sukai, telah mengembangkan solusi yang memungkinkan konstruksi _UI (user interface)_ aplikasi web modern sambil tetap mengg
```
Lainnya lebih memilih untuk tetap menggunakan bahasa _backend_ yang mereka sukai dan telah mengembangkan solusi yang memungkinkan konstruksi UI (_user interface_) aplikasi web modern sambil tetap menggunakan bahasa _backend_ pilihan mereka. Misalnya, di ekosistem [_Rails_](https://rubyonrails.org/), hal ini telah mendorong pembuatan _library_ seperti [_Turbo_](https://turbo.hotwired.dev/) [_Hotwire_](https://hotwired.dev/), dan [_Stimulus_](https://stimulus.hotwired.dev/).
```

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +#### Tumbuhnya Harapan
"Mengembangkan Ekspektasi" kayaknya lebih sesuai dengan isi paragraf

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +[Laravel Livewire](https://laravel-livewire.com) _framework_ untuk membangun _frontend_ bertenaga Laravel yang terasa dinamis, modern, dan hidup seperti _frontend_ yang dibuat dengan _framework_ Java
Laravel Livewire **adalah sebuah** _framework_

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Saat menggunakan Livewire, Anda akan membuat "komponen" Livewire yang _merender_ bagian terpisah dari _UI (user interface)_ Anda dan menampilkan metode dan data yang dapat dipanggil dan berinteraksi
- `me-_render_`
- `UI (_user interface_)`

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Seperti yang Anda lihat, Livewire memungkinkan Anda menulis atribut HTML baru seperti `wire:click` yang menghubungkan _frontend_ dan backend aplikasi Laravel Anda. Selain itu, Anda dapat _merender_ s
- `me-_render_`
- _backend_
-

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Bagi banyak orang, Livewire telah berevolusi pengembangan _frontend_ dengan Laravel, memungkinkan mereka untuk tetap berada dalam kenyamanan Laravel sambil membangun aplikasi web yang modern dan dina
- `me-_render_`

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Jika Anda baru menggunakan Laravel, sebaiknya pahami penggunaan dasar [views](/docs/{{version}}/views) dan [Blade](/docs/{{version}}/blade). Kemudian, lihat [dokumentasi Laravel Livewire](https://lar
- `_view_` -> italic singular

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +<a name="php-starter-kits" id="php-starter-kits"></a>
~~id="php-starter-kits"~~

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +<a name="using-vue-react" id="using-vue-react"></a>
~~id="using-vue-react"~~

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Namun, tanpa alat tambahan, memasangkan Laravel dengan Vue atau React akan membuat kita harus menyelesaikan berbagai masalah rumit seperti rute sisi klien, _hydration_ data, dan autentikasi. Rute sis
- "memasangkan" -> "memadukan"

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +<a name="inertia" id="inertia"></a>
~~id="inertia"~~

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Untungnya, Laravel menawarkan yang terbaik dari kedua dunia. [Inertia](https://inertiajs.com) menjembatani celah antara aplikasi Laravel Anda dan _frontend_ Vue atau React modern Anda, memungkinkan A
- menawarkan yang terbaik **pada** kedua dunia

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Setelah menginstal Inertia ke dalam aplikasi Laravel Anda, Anda akan menulis rute dan _controller_ seperti biasa. Namun, alih-alih mengembalikan templat _Blade_ dari _controller_ Anda, Anda akan meng
- _template_

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Seperti yang Anda lihat, Inertia memungkinkan Anda untuk memanfaatkan kekuatan penuh Vue atau React ketika membangun _frontend_ Anda, sambil menyediakan jembatan yang ringan antara _backend_ yang did
supaya lebih mudah dipahami:

"_backend_ ~~yang didukung oleh~~ Laravel dengan _frontend_ ~~yang didukung oleh~~ JavaScript"

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +#### Rendering Sisi Server
"_Render_ di Sisi Server" atau biarkan tetap "_Server-Side Rendering_"

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Jika Anda khawatir untuk menyelami Inertia karena aplikasi Anda membutuhkan _rendering_ sisi server, jangan khawatir. Inertia menawarkan [dukungan _rendering_ sisi server](https://inertiajs.com/serve
"..., **akan** sangat mudah untuk memastikan ...."

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Jika Anda ingin membangun _frontend_ menggunakan Inertia dan Vue / React, Anda dapat memanfaatkan [kit pemula breeze dan inertia](/docs/{{version}}/starter-kits#breeze-dan-inertia) untuk memulai peng
- Breeze dan Inertia -> huruf pertama kapital

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +<a name="bundling-assets" id="bundling-assets"></a>
~~id="bundling-assets"~~

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +## Aset Bundel
Membundel Aset

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Terlepas dari apakah Anda memilih untuk mengembangkan _frontend_ menggunakan _Blade_ dan Livewire atau Vue / React dan Inertia, Anda mungkin perlu memaketkan CSS aplikasi Anda ke dalam aset yang siap
- frontend lupa italic

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Secara _default_, Laravel menggunakan [Vite](https://vitejs.dev) untuk memaketkan aset Anda. Vite menyediakan waktu pembuatan secepat kilat dan Penggantian Modul Panas (_Hot Module Replacement/HMR_)
- _plugin_
- "yang memuat plugin Laravel Vite kami yang ringan **sehingga penggunaan Vite pada aplikasi Laravel adalah sebuah suka cita**"

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +Cara tercepat untuk memulai dengan Laravel dan Vite adalah dengan memulai pengembangan aplikasi Anda menggunakan [Laravel Breeze](/docs/{{version}}/starter-kits#laravel-breeze), starter kit kami yang
- backend lupa italic

2023-01-28 14:46 UTC, sensasi-delight commented on frontend.md
> +> Untuk dokumentasi yang lebih mendetail tentang cara menggunakan Vite dengan Laravel, silakan lihat [dokumentasi khusus tentang bundel dan kompilasi aset Anda] (/docs/{{versi}}/vite).
link nya jgan di translate wkwkw

2023-01-29 01:28 UTC, muchfahmiarif commented on frontend.md
> +Laravel adalah _framework backend_ yang menyediakan semua fitur yang Anda perlukan untuk membangun aplikasi web modern, seperti [_route_](/docs/{{version}}/routing), [validasi](/docs/{{version}}/vali
di KBBI ada pak [disini](https://cdn.discordapp.com/attachments/757901764359094322/1069065788255895562/image.png)

2023-01-29 01:44 UTC, muchfahmiarif commented on frontend.md
> +Secara _default_, Laravel menggunakan [Vite](https://vitejs.dev) untuk memaketkan aset Anda. Vite menyediakan waktu pembuatan secepat kilat dan Penggantian Modul Panas (_Hot Module Replacement/HMR_)
pak kalimat terakhir ditambah `sehingga penggunaan Vite pada aplikasi Laravel adalah sebuah suka cita`? :confused:

2023-01-29 01:45 UTC, muchfahmiarif commented on frontend.md
> +> Untuk dokumentasi yang lebih mendetail tentang cara menggunakan Vite dengan Laravel, silakan lihat [dokumentasi khusus tentang bundel dan kompilasi aset Anda] (/docs/{{versi}}/vite).
terlalu canggih translatornya :laughing:

2023-01-29 01:53 UTC, muchfahmiarif commented on frontend.md
> +Di Laravel, pendekatan menampilkan HTML ini masih dapat dicapai dengan menggunakan [_views_](/docs/{{version}}/views) dan [_Blade_](/docs/{{version}}/blade). _Blade_ adalah bahasa templating yang san
`templating` bisa pake italic ga pak? @sensasi-delight

2023-01-29 02:02 UTC, muchfahmiarif commented on frontend.md
> +<a name="php-starter-kits" id="php-starter-kits"></a>
jadi semua yg ada `id` dihilangkan saja pak?

2023-01-29 02:05 UTC, muchfahmiarif commented on frontend.md
> +#### Rendering Sisi Server
minta masukkannya kawan-kawan @wokeh @theozebua @MeizalunaWulandari

2023-01-29 03:23 UTC, MeizalunaWulandari approved these changes

2023-01-29 03:23 UTC, MeizalunaWulandari commented on frontend.md
> +#### Rendering Sisi Server
"Server-Side Rendering"

2023-01-29 03:25 UTC, sensasi-delight commented on frontend.md
> +Laravel adalah _framework backend_ yang menyediakan semua fitur yang Anda perlukan untuk membangun aplikasi web modern, seperti [_route_](/docs/{{version}}/routing), [validasi](/docs/{{version}}/vali
sori-sori wkwkwk

2023-01-29 03:25 UTC, sensasi-delight commented on frontend.md
> +Ada dua cara utama untuk menangani pengembangan _frontend_ saat membangun aplikasi dengan Laravel dan cara mana yang Anda pilih yang telah anda tentukan, apakah Anda ingin membangun _frontend_ dengan
masih membingungkan ya kalimat awalnya

2023-01-29 03:25 UTC, sensasi-delight commented on frontend.md
> +Saat membuat aplikasi dengan pendekatan ini, pengiriman formulir dan interaksi halaman lain biasanya menerima dokumen HTML yang (benar-benar) baru dari server kemudian seluruh halaman di-render ulang
`di-_render_`

2023-01-29 03:25 UTC, sensasi-delight commented on frontend.md
> +Lainnya lebih memilih untuk tetap menggunakan bahasa _backend_ yang mereka sukai dan telah mengembangkan solusi yang memungkinkan konstruksi UI (_user interface_) aplikasi web modern sambil tetap men
wah baru ngeh. Rails, Turbo, Hotwire, dan Stimulus gakusah italic karena sebuah nama

2023-01-29 03:25 UTC, sensasi-delight commented on frontend.md
> +<a name="php-starter-kits" id="php-starter-kits"></a>
betul, karena gak ada di file asalnya

2023-01-29 03:28 UTC, sensasi-delight commented on frontend.md
> +Secara _default_, Laravel menggunakan [Vite](https://vitejs.dev) untuk memaketkan aset Anda. Vite menyediakan waktu pembuatan secepat kilat dan Penggantian Modul Panas (_Hot Module Replacement/HMR_)
wkwkk menurutku gitu terjemahan yg mudah dimengerti

2023-01-30 11:55 UTC, sensasi-delight approved these changes
LGTM 🍻

2023-01-30 11:56 UTC, merged