translate menjadi indonesia pada console-test.md
lara-army/dokumentasi-laravel pull request #111
Opened 2023-01-30 15:09 UTC by muchfahmiarif

mohon di ripiw teman2

2023-01-30 16:00 UTC, sensasi-delight requested changes
Rangkuman:
- anda -> Anda
- _exit code_ -> kode _exit_

2023-01-30 16:00 UTC, sensasi-delight commented on console-tests.md
> +Selain menyederhanakan pengujian HTTP, Laravel menyediakan API sederhana untuk menguji dalam aplikasi anda yaitu [perintah konsol khusus](/docs/{{versi}}/artisan).
Laravel menyediakan API sederhana untuk menguji **perintah konsol kustom milik aplikasi Anda**

2023-01-30 16:00 UTC, sensasi-delight commented on console-tests.md
> +## Ekspektasi Masukan / Keluaran
Ekspektasi Input / _Output_

2023-01-30 16:00 UTC, sensasi-delight commented on console-tests.md
> +Laravel memungkinkan Anda untuk dengan mudah "menirukan" input pengguna untuk perintah konsol Anda menggunakan metode `expectsQuestion`. Selain itu, Anda dapat menentukan _exit code_ dan teks yang An
- Laravel memungkinkan Anda "menirukan" input dari pengguna untuk perintah konsol Anda dengan mudah menggunakan metode `expectsQuestion`.
- kode _exit_

2023-01-30 16:00 UTC, sensasi-delight commented on console-tests.md
> +Anda dapat menguji perintah ini dengan pengujian berikut yang menggunakan metode `expectsQuestion`, `expectsOutput`, `doesn'tExpectOutput`, `expectsOutputToContain`, `doesn'tExpectOutputToContain`, d
- Anda dapat menguji perintah-perintah tersebut dengan menggunakan metode
- doesn't -> doesnt

2023-01-30 16:00 UTC, sensasi-delight commented on console-tests.md
> +#### Harapan Konfirmasi
Ekspektasi Konfirmasi

2023-01-30 16:00 UTC, sensasi-delight commented on console-tests.md
> +Jika perintah Anda menampilkan tabel informasi menggunakan metode `table` pada Artisan, mungkin akan menjadi tidak praktis untuk menulis hasil ekspektasi pada seluruh tabel. Sebagai gantinya, Anda da
- tidak praktis untuk menulis **seluruh tabel pada ekspektasi hasil**.
- header tabel -> kop/kepala tabel
- data*/badan* tabel

2023-01-31 10:19 UTC, sensasi-delight approved these changes
LGTM 🍻

2023-01-31 15:06 UTC, theozebua approved these changes
LGTM 👍🏼

2023-01-31 21:26 UTC, merged