chore: menerjemahkan file vite.md
lara-army/dokumentasi-laravel pull request #112
Opened 2023-02-03 04:43 UTC by sensasi-delight

close #8 

rekan-rekan kontributor tersayang mohon meninjau hasil terjemahan yang telah saya lakukan. terimakasih banyak 🍻

2023-02-03 04:49 UTC, sensasi-delight reviewed
mohon menyesuaikan pembaharuan dari Laravel untuk menyelesaikan konflik.

2023-02-03 04:50 UTC, sensasi-delight commented
> mohon menyesuaikan pembaharuan dari Laravel untuk menyelesaikan konflik.

shap!

2023-02-04 03:08 UTC, theozebua requested changes

2023-02-04 03:08 UTC, theozebua commented on vite.md
> +## Instalasi & Pengaturan Awal
Judul tidak konsisten dengan daftar isi pada _line_: 4

2023-02-04 03:28 UTC, theozebua commented on vite.md
> +## Instalasi & Pengaturan Awal
Sudah diperbaiki 👍🏼 

[`178e23a`](https://github.com/lara-army/dokumentasi-laravel/pull/112/commits/178e23a9db79ec20fb7d9b37edde0fb63880d0d7)

2023-02-04 03:29 UTC, theozebua approved these changes

2023-02-04 05:11 UTC, MeizalunaWulandari approved these changes

2023-02-04 09:21 UTC, merged