coba di cek bang
lara-army/dokumentasi-laravel pull request #114
Opened 2023-02-10 03:33 UTC by AzzamSyakir

2023-02-10 03:38 UTC, sensasi-delight commented
Salam, @AzzamSyakir.

Terima kasih telah melakukan kontribusi. Silakan menunggu tim peninjau memeriksa hasil terjemahan Anda.
Anda dapat menerjemahkan halaman lain sembari menunggu hasil peninjauan.

Salam hangat, Zain.

2023-02-11 07:48 UTC, theozebua requested changes

2023-02-11 07:48 UTC, theozebua commented on .vscode/settings.json
> +}
`.vscode` itu jangan ikut di-_push_ ke GitHub, bisa dimasukkan ke `.gitignore` saja, atau gaperlu dibuat. _Setting_ di _code editor_ sendiri saja.

2023-02-11 10:37 UTC, MeizalunaWulandari commented on passport.md
> +Passport [service provider](/docs/{{version}}/providers)  mendaftarkan direktori migrasi database sendir,  jadi anda harus migrasi setelah menginstall package. migrasi passport akan membuat tabel di
Sendir, typo

2023-02-11 10:37 UTC, MeizalunaWulandari commented on passport.md
> +setyellah menjalankan `passport:install` command, tambahkan `Laravel\Passport\HasApiTokens` trait ke `App\Models\User` model.Trait ini akan memberikan beberapa metode helper ke model Anda yang memung
setyellah, typo juga

2023-02-11 10:37 UTC, MeizalunaWulandari commented on passport.md
> + Secara default, Passport mengeluarkan token akses yang masa berlakunya panjang yang kedaluwarsa setelah satu tahun. Jika Anda ingin mengkonfigurasi masa berlakunya token yang lebih lama / pendek, An
Boot masuki dalam ` aja kya biasa

2023-02-11 10:37 UTC, MeizalunaWulandari commented on passport.md
> +Kadang", mungkin kamu  ingin menyesuaikan rute yang didefinisikan oleh Passport. Untuk mencapainya, pertama kamu perlu mengabaikan rute yang didaftarkan oleh Passport dengan menambahkan Passport::ign
Kadang-kadang jangan disingkat

2023-02-11 10:37 UTC, MeizalunaWulandari commented on passport.md
> +Cara termudah untuk membuat client adalah menggunakan command Artisan passport:client. Perintah ini dapat digunakan untuk membuat client sendiri untuk menguji fungsi OAuth2 Anda. Ketika Anda menjalan
Sama ini passport:client masukin dalam `. 
Terus command artisan jadi perintah artisan biar sama kya terjemahan lain

2023-02-11 10:37 UTC, MeizalunaWulandari commented on passport.md
> +Jika Anda ingin memperbolehkan beberapa URL redirect untuk klien Anda, Anda dapat menentukannya menggunakan daftar yang dipisahkan dengan koma saat diminta URL oleh perintah passport:client. URL apa
Ini juga pake \` 
Sesuaiin aja pake aslinya pake \` ya ikutin aja

2023-07-09 12:31 UTC, wokeh requested changes
request gw samaan @MeizalunaWulandari

2023-10-19 11:47 UTC, ryugenxd commented
@sensasi-delight  bang kalau ikut berkontribusi tetapi dengan bantuan google transilit tapi dengan sedikit nalar boleh ga ?

2023-10-19 12:33 UTC, sensasi-delight commented
> @sensasi-delight bang kalau ikut berkontribusi tetapi dengan bantuan google transilit tapi dengan sedikit nalar boleh ga ?

@ryugenxd gak boleh, harus banyak nalarnya. hasil terjemahan mesin penerjemah seringnya di luar nalar. minimal diparafrasa dan dibaca ulang supaya tulisannya 'mengalir', nyambung semua tiap kata, kalimat, dan paragraf. lebih bagus lagi disesuaikan kata-katanya dengan kata umum zaman sekarang.

2024-05-06 13:02 UTC, closed without merging

2024-05-06 13:03 UTC, sensasi-delight commented
closing PR cause inactivity