Terjemahan untuk file urls.md
lara-army/dokumentasi-laravel pull request #98
Opened 2023-01-11 14:50 UTC by sensasi-delight

mohon rekan-rekan _colaborator_ meninjau terjemahan yang saya kerjakan. terima kasih.

2023-01-11 14:59 UTC, theozebua commented on urls.md
> +- [URL Untuk _Named Route_](#urls-for-named-routes)
Ini boleh juga jadi "URL Untuk Rute Bernama"

2023-01-11 16:57 UTC, wokeh approved these changes
ok, so far so good

2023-01-12 05:05 UTC, theozebua requested changes
Ada beberapa terjemahan yang sekiranya dapat diperbaiki / ditinjau ulang bang.

2023-01-12 05:05 UTC, theozebua commented on urls.md
> +Pengaturan nilai _default_ URL dapat mengganggu penanganan Laravel terhadap _binding_ model implisit. Oleh karena itu, Anda harus [memprioritaskan middleware Anda](/docs/{{version}}/middleware#sortin
- "... _binding_ model implisit. ..." 👉🏼 "... _binding_ model secara implisit. ..."
- _default_ 👉🏼 bawaan
- "... terjadi sebelum _middleware_ `SubstituteBindings` telah tercatat di dalam properti `$middlewarePriority` ..." 👉🏼 "... berjalan sebelum _middleware_ `SubstituteBindings` yang ada di dalam properti `$middlewarePriority` ..."

2023-01-12 09:55 UTC, sensasi-delight commented on urls.md
> +- [URL Untuk _Named Route_](#urls-for-named-routes)
aneh kurasa kalau ini bahasa indonesia semua bang. need a second opinion from @wokeh

2023-01-12 09:57 UTC, sensasi-delight commented on urls.md
> +- [URL Untuk _Named Route_](#urls-for-named-routes)
atau main tanda kurung saja ya, misal:

"URL Untuk _Named Route_ (Rute Bernama)"

tapi main kurung hanya bisa di paragraf saja, gabisa di heading/toc

2023-01-12 10:02 UTC, sensasi-delight commented on urls.md
> +- [URLs Untuk Aksi _Controller_](#urls-for-controller-actions)
untuk "URLs" sudah pasti kelewat ini wkwkw, nanti aku ubah jadi "URL"

2023-01-12 10:03 UTC, sensasi-delight commented on urls.md
> +- [Nilai _Default_](#default-values)
dalam percakapan "Nilai Dasar/Bawaan" kayaknya gak sepadan dengan "Nilai Default" ya.

need a second opinion @wokeh

2023-01-12 10:04 UTC, sensasi-delight commented on urls.md
> +Laravel menyediakan beberapa _helper_ untuk mendampingi Anda dalam menghasilkan URL untuk aplikasi Anda. _Helper_ ini akan sangat berguna ketika membuat pranala (_link_) pada _template_ dan respons A
"_redirect_" vs "pengalihan"

cc: @wokeh

2023-01-12 10:05 UTC, sensasi-delight commented on urls.md
> +_Helper_ `url` dapat digunakan untuk menghasilkan URL untuk aplikasi Anda. URL yang dihasilkan akan secara otomatis menggunakan skema (HTTP atau HTTPS) dan _host_ dari _request_ yang saat ini ditanga
> "... request ..." 👉🏼 "... permintaan ..."
cc: @wokeh 

> "... yang saat ini ditangani oleh aplikasi:" 👉🏼 "... yang saat ini sedang ditangani oleh aplikasi:"
agreed ✅

2023-01-12 10:12 UTC, sensasi-delight commented on urls.md
> +    // Mengambil URL penuh dari request sebelumnya...
~~"penuh"~~ "lengkap" ✔

"request" vs "permintaan"

cc @wokeh

2023-01-12 10:16 UTC, sensasi-delight commented on urls.md
> +Semua _method_ ini dapat diakses via [_facade_](/docs/{{version}}/facades) `URL`:
aku merasa (misal) "metode milik kelas" gak sepadan sama "_method_ milik _class_" wkwkwk sering bimbang kalau nerjemahin ini, really need second opinion from @wokeh

2023-01-12 10:18 UTC, sensasi-delight commented on urls.md
> +## URL Untuk _Named Route_
same as previous

2023-01-12 10:19 UTC, sensasi-delight commented on urls.md
> +_Helper_ `route` dapat digunakan untuk menghasilkan URL ke [_named routes_](/docs/{{version}}/routing#named-routes). Rute bernama memungkinkan Anda untuk menghasilkan URL tanpa harus ke URL aktual ya
> * "... menghasilkan URL ke [_named routes_](/docs/%7B%7Bversion%7D%7D/routing#named-routes)." 👉🏼 "... menghasilkan URL ke [rute bernama](/docs/%7B%7Bversion%7D%7D/routing#named-routes)."

same as previous

> * "... pemanggilan _function_" 👉🏼 "... pemanggilan fungsi"

"_function_" vs "fungsi". cc @wokeh

2023-01-12 10:22 UTC, sensasi-delight commented on urls.md
> +     * middleware yang terdaftar disini dapat ditambatkan pada rute biasa dan rute grup.
"secara individu" jadi membinggungkan.

cc @wokeh ?

2023-01-12 11:14 UTC, sensasi-delight commented on urls.md
> +Anda akan sering membuat URL menggunakan _route key_ (biasanya _primary key_) dari [model Eloquent](/docs/{{version}}/eloquent). Untuk alasan ini, Anda dapat mengoper model Eloquent sebagai nilai par
cc @wokeh ?

2023-01-12 11:14 UTC, sensasi-delight commented on urls.md
> +Laravel memungkinkan Anda untuk membuat URL yang "ditandatangani" (_signed URL_) untuk _named route_ secara mudah. URL ini memiliki hash "signature" yang ditambahkan ke _string_ kueri yang memungkink
same as previous

2023-01-12 11:16 UTC, sensasi-delight commented on urls.md
> +Misalnya, Anda mungkin menggunakan URL yang "ditandatangani" ini untuk mengimplementasikan tautan "berhenti berlangganan" yang dapat diakses publik, yang diemailkan ke pelanggan Anda. Untuk membuat U
same as previous

2023-01-12 11:17 UTC, sensasi-delight commented on urls.md
> +#### Validasi terhadap _Request_ dari _Signed Route_
same as previous

2023-01-12 11:19 UTC, sensasi-delight commented on urls.md
> +Terkadang, Anda mungkin perlu mengizinkan _frontend_ dari aplikasi Anda untuk menambahkan data ke URL yang ditandatangani ini, seperti saat melakukan _pagination_ dari sisi klien. Oleh karena itu, An
same as previous

2023-01-12 11:20 UTC, sensasi-delight commented on urls.md
> +Alih-alih memvalidasi URL yang ditandatangani menggunakan _instance_ _request_ yang masuk, Anda juga dapat menugaskan  [_middleware_](/docs/{{version}}/middleware) `Illuminate\Routing\Middleware\Vali
same as previous

2023-01-12 11:26 UTC, sensasi-delight commented on urls.md
> +## URL untuk Aksi _Controller_
same as previous

2023-01-12 11:26 UTC, sensasi-delight commented on urls.md
same as previous

2023-01-12 11:28 UTC, theozebua commented on urls.md
> +- [URL Untuk _Named Route_](#urls-for-named-routes)
> aneh kurasa kalau ini bahasa indonesia semua bang. need a second opinion from @wokeh

Memang bang, sebenarnya memang aneh kalau diterjemahin ke bahasa Indonesia semua 😆 
Tapi ya itu, karena ini tadi kan menerjemahkan dokumentasi Laravel dari bahasa Inggris ke bahasa Indonesia.

2023-01-12 11:30 UTC, theozebua commented on urls.md
> +- [URL Untuk _Named Route_](#urls-for-named-routes)
Atau boleh juga kita tidak usah menerjemahkan istilah-istilah yang ada. Apalagi yang sudah _familiar_.

2023-01-12 12:04 UTC, sensasi-delight commented on urls.md
> +- [URL Untuk _Named Route_](#urls-for-named-routes)
> Atau boleh juga kita tidak usah menerjemahkan istilah-istilah yang ada. Apalagi yang sudah _familiar_.

nah "familiar" ini yang tricky bang, terlalu subjektif sehingga perlu banyak masukkan dari pembaca xixixi

2023-01-12 12:06 UTC, sensasi-delight commented on urls.md
> +_Helper_ `route` dapat digunakan untuk menghasilkan URL ke [_named routes_](/docs/{{version}}/routing#named-routes). Rute bernama memungkinkan Anda untuk menghasilkan URL tanpa harus ke URL aktual ya
> alau untuk fungsi sih sepertinya oke oke aja bang, karena dalam pembelajaran kami diperkuliahan dulu juga menggunakan kata "fungsi". Bahkan di dalam matematika juga menggunakan kata "fungsi", seperti _f(x)_.
> Bagaimana menurutmu @wokeh ?

benar juga ya, dosen-dosen dulu nyebutnya "fungsi program" dan kita paham-paham saja.

2023-01-13 13:38 UTC, wokeh commented on urls.md
> +- [URL Untuk _Named Route_](#urls-for-named-routes)
iya, sering nemu istilah2 IT yg susah di-translate ke bhs indonesia krn kadang malah jadi membingungkan, kayak 'deployment', 'dispatch', 'instance', 'instantiation', sebagian krn belum ada padanan yg tepat, sebagian lagi padanannya mengaburkan maknanya, dsb.

utk istilah 'named route' sy pilih tetap ditulis apa adanya

2023-01-15 16:54 UTC, theozebua commented on urls.md
> +- [URL Untuk _Named Route_](#urls-for-named-routes)
Baiklah kalau begitu 👍🏼

2023-01-15 16:57 UTC, theozebua commented
Bagaimana? Apakah sudah cocok semuanya? @wokeh

2023-01-18 03:03 UTC, sensasi-delight commented on urls.md
> +- [URL Untuk _Named Route_](#urls-for-named-routes)
*"... _named route_ ..."* pertama yang disebutkan di dalam paragraf telah diubah menjadi *"... _named route_ (rute bernama) ..."* sehingga penggunaan kedua kalimat tersebut secara bergantian pada paragraf selanjutnya—diharapkan—tidak akan menyebabkan kebingungan.

perubahan dapat dilihat pada: https://github.com/lara-army/dokumentasi-laravel/pull/98/commits/4b230ccb88204bc2251a8490e572b3496394a3b4 baris 54

2023-01-18 03:03 UTC, sensasi-delight commented on urls.md
> +- [Nilai _Default_](#default-values)
*"... nilai _default_ ..."* pertama yang disebutkan di dalam paragraf telah diubah menjadi *"... nilai _default_ (bawaan) ..."* sehingga penggunaan kedua kalimat tersebut secara bergantian pada paragraf selanjutnya—diharapkan—tidak akan menyebabkan kebingungan.

perubahan dapat dilihat pada: https://github.com/lara-army/dokumentasi-laravel/pull/98/commits/4b230ccb88204bc2251a8490e572b3496394a3b4 baris 183

2023-01-18 03:03 UTC, sensasi-delight commented on urls.md
> +Laravel menyediakan beberapa _helper_ untuk mendampingi Anda dalam menghasilkan URL untuk aplikasi Anda. _Helper_ ini akan sangat berguna ketika membuat pranala (_link_) pada _template_ dan respons A
*"... _redirect_ ..."* pertama yang disebutkan di dalam paragraf telah diubah menjadi *"... _redirect_ (pengalihan) ..."* sehingga penggunaan kedua kalimat tersebut secara bergantian pada paragraf selanjutnya—diharapkan—tidak akan menyebabkan kebingungan.

perubahan dapat dilihat pada: https://github.com/lara-army/dokumentasi-laravel/pull/98/commits/4b230ccb88204bc2251a8490e572b3496394a3b4 baris 15

2023-01-18 03:04 UTC, sensasi-delight commented on urls.md
> +_Helper_ `url` dapat digunakan untuk menghasilkan URL untuk aplikasi Anda. URL yang dihasilkan akan secara otomatis menggunakan skema (HTTP atau HTTPS) dan _host_ dari _request_ yang saat ini ditanga
*"... _request_ ..."* pertama yang disebutkan di dalam paragraf telah diubah menjadi *"... _request_ (permintaan) ..."* sehingga penggunaan kedua kalimat tersebut secara bergantian pada paragraf selanjutnya—diharapkan—tidak akan menyebabkan kebingungan.

perubahan dapat dilihat pada: https://github.com/lara-army/dokumentasi-laravel/pull/98/commits/4b230ccb88204bc2251a8490e572b3496394a3b4 baris 23

2023-01-18 03:04 UTC, sensasi-delight commented on urls.md
> +Semua _method_ ini dapat diakses via [_facade_](/docs/{{version}}/facades) `URL`:
*"... _method_ ..."* pertama yang disebutkan di dalam paragraf telah diubah menjadi *"... metode (_method_) ..."* sehingga penggunaan kedua kalimat tersebut secara bergantian pada paragraf selanjutnya—diharapkan—tidak akan menyebabkan kebingungan.

perubahan dapat dilihat pada: https://github.com/lara-army/dokumentasi-laravel/pull/98/commits/4b230ccb88204bc2251a8490e572b3496394a3b4 baris 45

2023-01-18 03:04 UTC, sensasi-delight commented on urls.md
> +_Helper_ `route` dapat digunakan untuk menghasilkan URL ke [_named routes_](/docs/{{version}}/routing#named-routes). Rute bernama memungkinkan Anda untuk menghasilkan URL tanpa harus ke URL aktual ya
*"... _function_ ..."* pertama yang disebutkan di dalam paragraf telah diubah menjadi *"... fungsi (_function_) ..."* sehingga penggunaan kedua kalimat tersebut secara bergantian pada paragraf selanjutnya—diharapkan—tidak akan menyebabkan kebingungan.

perubahan dapat dilihat pada: https://github.com/lara-army/dokumentasi-laravel/pull/98/commits/4b230ccb88204bc2251a8490e572b3496394a3b4 baris 54

2023-01-18 03:05 UTC, sensasi-delight commented on urls.md
> +Setelah Anda mendaftarkan _middleware_ di kernel Anda, Anda dapat manambatkannya pada sebuah _route_. Jika permintaan yang masuk tidak memiliki tanda tangan yang valid, _middleware_ akan secara otoma
*"... _route_ ..."* pertama yang disebutkan di dalam paragraf telah diubah menjadi *"... rute (_route_) ..."* sehingga penggunaan kedua kalimat tersebut secara bergantian pada paragraf selanjutnya—diharapkan—tidak akan menyebabkan kebingungan.

perubahan dapat dilihat pada: https://github.com/lara-army/dokumentasi-laravel/pull/98/commits/4b230ccb88204bc2251a8490e572b3496394a3b4 baris 54

2023-01-18 03:05 UTC, sensasi-delight commented on urls.md
> +Ketika seseorang mengunjungi _signed_ URL yang telah kedaluwarsa, mereka akan menerima halaman eror yang umum untuk kode status HTTP `403`. Namun, Anda dapat menyesuaikan perilaku ini dengan mendefin
Untuk kesesuaian kalimat dan contoh kode program maka kalimat:

Anda dapat menyesuaikan perilaku ini dengan mendefinisikan _closure_ "renderable" khusus

telah saya ubah menjadi:

Anda dapat menyesuaikan perilaku ini dengan mendefinisikan sebuah _closure_ pada metode `renderable` khusus

2023-01-18 09:40 UTC, MeizalunaWulandari approved these changes
Generating ditranslate jadi "membuat" lebih nyaman dari "menghasilkan"

2023-01-18 09:40 UTC, MeizalunaWulandari commented on urls.md
> +Laravel menyediakan beberapa _helper_ untuk mendampingi Anda dalam menghasilkan URL untuk aplikasi Anda. _Helper_ ini akan sangat berguna ketika membuat pranala (_link_) pada _template_ dan respons A
laravel menyediakan beberapa _helper_ untuk mendampingi anda dalam menghasilkan url untuk aplikasi anda.  👉 Laravel menyediakan beberapa _helper_ untuk mendampingi Anda dalam pembuatan URL untuk aplikasi Anda.

2023-01-18 13:30 UTC, sensasi-delight commented on urls.md
> +Laravel menyediakan beberapa _helper_ untuk mendampingi Anda dalam menghasilkan URL untuk aplikasi Anda. _Helper_ ini akan sangat berguna ketika membuat pranala (_link_) pada _template_ dan respons A
done at https://github.com/lara-army/dokumentasi-laravel/pull/98/commits/8287795d8dc751029fe7ac7e246c6637eff4209f

2023-01-18 13:33 UTC, merged