[9.x] Terjemahan untuk file csrf.md
lara-army/dokumentasi-laravel pull request #99
Opened 2023-01-14 01:47 UTC by sensasi-delight

close #2 

rekan-rekan kolaborator tersayang, dimohon untuk meninjau terjemahan yang saya kerjakan. terima kasih.

2023-01-14 11:47 UTC, wokeh requested changes
Great job bro, ini request saya

Jika Anda tidak terbiasa dengan **pemalsuan permintaan lintas-situs**
Jika anda belum akrab dengan istilah **cross-site request forgery**

Bayangkan aplikasi Anda memiliki **rute** yang menerima **permintaan** POST
Bayangkan apabila aplikasi Anda memiliki **route** yang menerima **request** POST

kita perlu memeriksa setiap **permintaan**
kita perlu memeriksa setiap **request**

Cookie ini **terutama** dikirim **sebagai kenyamanan pengembang**
Cookie ini **pada dasarnya** dikirim **untuk memberikan kenyamanan kepada pengembang**

kalo ada keberatan, please let me know

2023-01-14 12:23 UTC, sensasi-delight commented
done @wokeh

2023-01-15 12:28 UTC, theozebua approved these changes
Nice 👍🏼

2023-01-17 01:35 UTC, MeizalunaWulandari commented on csrf.md
> +Jika Anda tidak terbiasa dengan pemalsuan _request_ lintas-situs (CSRF), mari kita bahas contoh bagaimana kerentanan ini dapat dieksploitasi. Bayangkan aplikasi Anda memiliki rute `/pengguna/email` y
Jika anda masih awam dengan csrf.

Kayanya csrf ga perlu di translate dh cukup italic aja

2023-01-17 01:55 UTC, sensasi-delight commented on csrf.md
> +Jika Anda tidak terbiasa dengan pemalsuan _request_ lintas-situs (CSRF), mari kita bahas contoh bagaimana kerentanan ini dapat dieksploitasi. Bayangkan aplikasi Anda memiliki rute `/pengguna/email` y
hal tersebut sudah direvisi pada https://github.com/lara-army/dokumentasi-laravel/pull/99/commits/919574847893160069b62b84ca8efe30932db3cb

2023-01-17 06:25 UTC, MeizalunaWulandari approved these changes

2023-01-17 06:35 UTC, merged